# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: chat_app_development
  username: postgres

  # The password associated with the PostgreSQL role (username).
  password: pavel

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 5432
# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    encoding: unicode
